### PR TITLE
Play with cards assign 5

### PR DESCRIPTION
**Pull request by rkdesala**
Screenshot (73)

### CODE REVIEW

**Review by ShehbazWaasi20 — APPROVED** [review]
Correct

**Review by ShehbazWaasi20 — CHANGES_REQUESTED** [review]
Check this code once keep your code in the function and check it think for different test cases and runit t

**Review by ShehbazWaasi20 — APPROVED** [review]
Correct

**Review by ShehbazWaasi20 — APPROVED** [review]
Correct

**Review by ShehbazWaasi20 — APPROVED** [review]
Correct

**Review by saikiransathpadi — APPROVED** [review]

**Pull request merged**
